version: "2"
plugins:
  phpcodesniffer:
    enabled: true
    channel: beta
    config:
      standard: "PSR12"
exclude_patterns:
  - "app/Console/"
  - "public/"
  - "resources/"
  - "storage/"
  - "tests/"
  - "vendor/"
