version: 8
preset: laravel

tab-width: 4
use-tabs: false

enabled:
  - concat_with_spaces

disabled:
  - concat_without_spaces
  - not_operator_with_successor_space

finder:
  exclude:
    - "storage"
    - "vendor"
  name: "*.php"
  not-name:
    - "*.blade.php"
    - "_ide_helper.php"
