os: linux
dist: bionic
language: php
php: 8.0
branches:
  only:
    - master

cache:
  directories:
    - vendor

jobs:
  include:
    - stage: test
      install:
        - php -r "file_exists('.env') || copy('.env.example', '.env');"
        - composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      before_script:
        - APP_KEY=$(php -r 'echo md5(uniqid());')
        - echo APP_KEY=$APP_KEY
        - echo APP_KEY=$APP_KEY >> .env
        - php artisan jwt:secret
        - touch storage/app/database.sqlite
        - chmod +x artisan
        - ./artisan migrate
      script:
        - vendor/bin/phpunit
