os: linux
dist: bionic
language: php
php: 8.0
branches:
  only:
    - master

cache:
  directories:
    - vendor

jobs:
  include:
    - stage: test
      install:
        - php -r "file_exists('.env') || copy('.env.example', '.env');"
        - composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      before_script:
        - APP_KEY=$(php -r 'echo md5(uniqid());')
        - echo APP_KEY=$APP_KEY
        - echo APP_KEY=$APP_KEY >> .env
        - php artisan jwt:secret
        - touch storage/app/database.sqlite
        - chmod +x artisan
        - ./artisan migrate
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover clover.xml
        - find . -name clover.xml
      after_script:
        - ./cc-test-reporter after-build --coverage-input-type clover --exit-code $TRAVIS_TEST_RESULT
