name: E2E Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  e2e:

    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@b7d1d9c9a92d8d8463ce36d7f60da34d461724f8
        with:
          php-version: '8.0'
          coverage: none

      - uses: actions/checkout@v2

      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Generate key
        run: |
          APP_KEY=$(php -r 'echo md5(uniqid());')
          echo APP_KEY=$APP_KEY
          echo APP_KEY=$APP_KEY >> .env
          php artisan jwt:secret

      - name: Create Database
        run: |
          mkdir -p database
          touch storage/app/database.sqlite
          php artisan migrate

      #- name: Setup tmate session
      #  uses: mxschmitt/action-tmate@v3

      - name: Start PHP server
        run: DB_DATABASE="`pwd`/storage/app/database.sqlite" php -S 127.0.0.1:8000 -t public >/dev/null 2>&1 &

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: DB_DATABASE="`pwd`/storage/app/database.sqlite" vendor/bin/phpunit --group e2e tests/E2E/EndPointsTest.php
